[[redirects]]
  from = "/"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/f4e3d2c1-b6a5-48c7-9d8e-0f1e2d3c4b5a"
  to = "/criarconta.html"
  status = 200

[[redirects]]
  from = "/9a8b7c6d-5e4f-3a2b-1c0d-9e8f7a6b5c4d"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f"
  to = "/termos.html"
  status = 200

[[redirects]]
  from = "/b0a1c2d3-e4f5-6a7b-8c9d-0e1f2a3b4c5d"
  to = "/recuperar.html"
  status = 200

  [[redirects]]
  from = "/d5e6f7a8-b9c0-1d2e-3f4a-5b6c7d8e9f0a"
  to = "/main2.html"
  status = 200